[package]
name = "git-mob-tool"
version = "1.3.1"
authors = ["Mubashwer Salman Khurshid"]
edition = "2021"
description = "A CLI app which can help users automatically add co-author(s) to git commits for pair/mob programming"
readme = "README.md"
repository = "https://github.com/Mubashwer/git-mob"
license = "MIT"
keywords = [
  "git",
  "cli",
  "pair-programming",
  "mob-programming"
]
categories = ["command-line-interface", "command-line-utilities"]
include = [
  "src/**/*",
  "Cargo.lock",
  "Cargo.toml",
  "LICENSE",
  "prepare-commit-msg",
  "README.md"
]

[[bin]]
name = "git-mob"
path = "src/main.rs"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
inquire = "0.6.0"

[dev-dependencies]
assert_cmd = "2.0.10"
mockall = "0.11.3"
predicates = "3.0.1"
serial_test = "2.0.0"
