[package]
name = "git-mob"
version = "0.1.0"
authors = ["Mubashwer Salman Khurshid"]
edition = "2021"
description = "A CLI app which can help users automatically add co-author(s) to git commits for pair/mob programming."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
inquire = "0.6.0"

[dev-dependencies]
mockall = "0.11.3"
