on:
  workflow_run:
    workflows: [build]
    types:
      - completed
    branches: [main]

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          package-name: release-please-action
          release-type: rust
          token: ${{ secrets.GH_TOKEN }}
          prerelease: true

  upload-binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: git-mob
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: git-mob
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: git-mob.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: git-mob.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: git-mob
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: git-mob
    runs-on: ${{ matrix.os }}
    if: ${{ needs.release-please.outputs.releases_created }}
    needs: [release-please]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Setup cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download aarch64-linux-musl-gcc linker
        if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
        run: curl -sL https://musl.cc/aarch64-linux-musl-cross.tgz | tar xvzf -

      - name: Run cargo build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Archive binary
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: tar
          directory: target/${{ matrix.target }}/release
          path: ${{ matrix.artifact_name }}
          filename: git-mob-${{ matrix.target }}.tar.gz

      - name: Upload archived binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: target/${{ matrix.target }}/release/git-mob-${{ matrix.target }}.tar.gz
          tag: ${{ needs.release-please.outputs.tag_name }}

  publish-cargo:
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created }}
    needs: [release-please]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo publish
        run: cargo publish --no-verify --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
