on:
  workflow_run:
    workflows: [build]
    types:
      - completed
    branches: [main]

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          package-name: release-please-action
          release-type: rust
          token: ${{ secrets.GH_TOKEN }}
          prerelease: true
